COMMAND_ENABLE = no
CONSOLE_ENABLE = no
LTO_ENABLE = yes				# reduces files size dramatically
VPATH  +=  keyboards/bm40hsrgb/keymaps/atanas/g/
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = yes
EXTRAKEY_ENABLE = yes # Audio control and System control
UNICODE_ENABLE = yes
NKRO_ENABLE = yes
# AUDIO_ENABLE = yes
MIDI_ENABLE = yes
